### ISSUE TITLE
CDD Errors

### ISSUE THREAD

**Issue by chiluf** [ARCCSS-extremes/climpact2#50]
Dear Nicholas,
I trust you are doing great.

I am running the latest ClimPACT2 to calculate the cdd indices for a station in Zambia. However, i am getting constant cdd values for all the years. i have attached the station data and the output from the  ClimPACT2 qc.

regards

[Kabwe001.zip](https://github.com/ARCCSS-extremes/climpact2/files/1843644/Kabwe001.zip)
[KABWE001.txt](https://github.com/ARCCSS-extremes/climpact2/files/1843652/KABWE001.txt)

**Comment by nangombe** [comment]
Dear Nicholas,

Please help me. I calculate several temperature and precipitation based extreme indices using CMIP5 models. However, I am getting weird results for CDDs i.e. the values for some points are too high >3000days for CDD_ANN, strange since a year has 365 days. And also viewing the .nc file, it doesn't show boundary lines like other extremes do.

I have attached an example file for CDD for your reference. I have also attached a file for CWD for comparison purposes calculated from the same data. The CWD results looks somewhat OK.



[cdd_ANN_ACCESS1-0_historical_r1i1p1_1960-2005.zip](https://github.com/ARCCSS-extremes/climpact2/files/2560733/cdd_ANN_ACCESS1-0_historical_r1i1p1_1960-2005.zip)
[cwd_ANN_ACCESS1-0_historical_r1i1p1_1960-2005.zip](https://github.com/ARCCSS-extremes/climpact2/files/2560734/cwd_ANN_ACCESS1-0_historical_r1i1p1_1960-2005.zip)

**Comment by heroldn** [comment]
Hi Nangombe

I am here in Cebu and have received a nudge to respond to you :). Apologies for the delay, I am now working on this in a volunteer capacity. For your problem, I believe cdd is doing as it should. What it is currently doing is allowing runs of dry days to cross years. Thus if you have 5 years of completely dry days then you'll get 5*365 in your cdd. And it looks like you get these really dry periods in the central Sahara which makes sense.

In climpact2.etsci-functions.r, please search "climdex.cdd <- function" and there is flag called "spells.can.span.years=TRUE". Change this to FALSE, rerun climpact and tell me if that gives you the values you expect.

Cheers

Nick.

**Comment by heroldn** [comment]
Hi Chiluf

Apologies for this delay too. It looks like the 29th day of each month is missing. So the maximum dry day run (cdd) is always maxing out at one month (30 days), which is the value you're getting in most years. This seems like an error and I assume you would have data for the 29th day of most months. Fill these out and see how you go.

Also, I notice your input file has -99 instead of -99.9 for missing values so your temperature results are incorrect.

Cheers

Nick.
